name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      # Step 4: Set up Java Development Kit (JDK) for SonarCloud scanning
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 5: Linting step to ensure code quality
      - name: Run linter
        run: npm run lint
        continue-on-error: true  # Optional: don't fail the build if linting fails

      # Step 6: SonarCloud Analysis for static code analysis and security checks
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.sources=./backend 
            -Dsonar.host.url=https://sonarcloud.io

      # Step 7: Dependency Vulnerability Scanning
      - name: Audit dependencies for vulnerabilities
        run: npm audit --audit-level=high
        continue-on-error: true  # This won't fail the build, but you'll see if there are any issues

      # Step 8: Security Analysis - OWASP ZAP or other tools (Optional)
      # - name: Run OWASP ZAP Scan
      #   run: |
      #     docker run -v $(pwd):/zap/wrk -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:3000 -r zap_report.html
      #   continue-on-error: true

      # Step 9: Test Run (if applicable)
      # If you add unit or integration tests later, use something like this:
      # - name: Run tests
      #   run: npm test
